# Generated by Django 5.1.6 on 2025-02-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('motivation', 'Motivation'), ('humor', 'Humor'), ('tv_movies', 'TV & Movies'), ('philosophy', 'Philosophy')], max_length=50)),
            ],
        ),
    ]
